version: '3.7'

services:
  gcs:
    image: fsouza/fake-gcs-server
    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 4443:4443
    volumes:
      - ./data:/data:cached
    command: --scheme http --public-host localhost